package com.wukong.examples.model;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wk_course
 */
public class Course implements Serializable {
    /**
     * Database Column Remarks:
     *   课程id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.course_id")
    private Long courseId;

    /**
     * Database Column Remarks:
     *   课程
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.course_name")
    private String courseName;

    /**
     * Database Column Remarks:
     *   记录创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.gmt_create")
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   记录修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.gmt_modified")
    private Date gmtModified;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: wk_course")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.course_id")
    public Long getCourseId() {
        return courseId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.course_id")
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.course_name")
    public String getCourseName() {
        return courseName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.course_name")
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.gmt_create")
    public Date getGmtCreate() {
        return gmtCreate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.gmt_create")
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.gmt_modified")
    public Date getGmtModified() {
        return gmtModified;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_course.gmt_modified")
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: wk_course")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", courseId=").append(courseId);
        sb.append(", courseName=").append(courseName);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}