package com.wukong.examples.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wk_student_scores
 */
public class StudentScores implements Serializable {
    /**
     * Database Column Remarks:
     *   学生详细id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.student_scores_id")
    private Long studentScoresId;

    /**
     * Database Column Remarks:
     *   学生id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.student_info_id")
    private Long studentInfoId;

    /**
     * Database Column Remarks:
     *   课程编号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.course_id")
    private Long courseId;

    /**
     * Database Column Remarks:
     *   数值：带小数点的
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.score")
    private BigDecimal score;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: wk_student_scores")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.student_scores_id")
    public Long getStudentScoresId() {
        return studentScoresId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.student_scores_id")
    public void setStudentScoresId(Long studentScoresId) {
        this.studentScoresId = studentScoresId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.student_info_id")
    public Long getStudentInfoId() {
        return studentInfoId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.student_info_id")
    public void setStudentInfoId(Long studentInfoId) {
        this.studentInfoId = studentInfoId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.course_id")
    public Long getCourseId() {
        return courseId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.course_id")
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.score")
    public BigDecimal getScore() {
        return score;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_scores.score")
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: wk_student_scores")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentScoresId=").append(studentScoresId);
        sb.append(", studentInfoId=").append(studentInfoId);
        sb.append(", courseId=").append(courseId);
        sb.append(", score=").append(score);
        sb.append("]");
        return sb.toString();
    }
}