package com.wukong.examples.model;

import java.io.Serializable;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wk_student_info
 */
public class StudentInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   学生详细id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.student_info_id")
    private Long studentInfoId;

    /**
     * Database Column Remarks:
     *   学生id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.student_id")
    private Long studentId;

    /**
     * Database Column Remarks:
     *   qq号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.qq")
    private String qq;

    /**
     * Database Column Remarks:
     *   wx号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.wx")
    private String wx;

    /**
     * Database Column Remarks:
     *   手机号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.mobil")
    private String mobil;

    /**
     * Database Column Remarks:
     *   地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.address")
    private String address;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: wk_student_info")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.student_info_id")
    public Long getStudentInfoId() {
        return studentInfoId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.student_info_id")
    public void setStudentInfoId(Long studentInfoId) {
        this.studentInfoId = studentInfoId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.student_id")
    public Long getStudentId() {
        return studentId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.student_id")
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.qq")
    public String getQq() {
        return qq;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.qq")
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.wx")
    public String getWx() {
        return wx;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.wx")
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.mobil")
    public String getMobil() {
        return mobil;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.mobil")
    public void setMobil(String mobil) {
        this.mobil = mobil == null ? null : mobil.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.address")
    public String getAddress() {
        return address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: wk_student_info.address")
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: wk_student_info")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentInfoId=").append(studentInfoId);
        sb.append(", studentId=").append(studentId);
        sb.append(", qq=").append(qq);
        sb.append(", wx=").append(wx);
        sb.append(", mobil=").append(mobil);
        sb.append(", address=").append(address);
        sb.append("]");
        return sb.toString();
    }
}